[package]
name = "chip_8_emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
eframe = "0.33.3"
egui = "0.33.3"
egui_dock = "0.18.0"
getrandom = { version = "0.4.2", features = ["wasm_js"] }
log = "0.4.29"
rand = "0.10.0"
wasm-bindgen = "0.2.114"
wasm-bindgen-futures = "0.4.64"
web-sys = { version = "0.3.91", features = ["Window", "Document", "HtmlElement", "HtmlCanvasElement", "Element"] }
